import os
from dotenv import load_dotenv

load_dotenv()


class Settings:
    GROQ_API_KEY: str = os.getenv("GROQ_API_KEY", "")
    GROQ_LLM_MODEL: str = os.getenv("GROQ_LLM_MODEL", "qwen/qwen3.6-27b")
    GROQ_AGENT_MODEL: str = os.getenv("GROQ_AGENT_MODEL", "openai/gpt-oss-20b")
    GROQ_STT_MODEL: str = os.getenv("GROQ_STT_MODEL", "whisper-large-v3")
    GROQ_TTS_MODEL: str = os.getenv("GROQ_TTS_MODEL", "canopylabs/orpheus-v1-english")
    TTS_VOICE: str = os.getenv("TTS_VOICE", "autumn")
    DATABASE_URL: str = os.getenv("DATABASE_URL", "sqlite:///chat.db")

    LLM_TEMPERATURE: float = 0.7
    LLM_MAX_TOKENS: int = 2048
    LLM_TOP_P: float = 1.0

    STT_TEMPERATURE: float = 0.0
    STT_PROMPT: str = os.getenv("STT_PROMPT", "")
    STT_LANGUAGE: str = os.getenv("STT_LANGUAGE", "en")


    # --- reSpeaker Clip input ---
    VOICE_INPUT_MODE: str = os.getenv("VOICE_INPUT_MODE", "both")
    CLIP_BLE_ADDRESS: str = os.getenv("CLIP_BLE_ADDRESS", "")
    CLIP_BLE_NAME: str = os.getenv("CLIP_BLE_NAME", "Clip")
    CLIP_RECORD_MODE: str = os.getenv("CLIP_RECORD_MODE", "enhanced")
    CLIP_STATUS_INTERVAL: int = int(os.getenv("CLIP_STATUS_INTERVAL", "5"))
    CLIP_DOWNLOAD_TIMEOUT: int = int(os.getenv("CLIP_DOWNLOAD_TIMEOUT", "300"))
    CLIP_TEMP_DIR: str = os.getenv("CLIP_TEMP_DIR", "clip_audio")
    CLIP_MAX_FAILED_ARTIFACTS: int = int(os.getenv("CLIP_MAX_FAILED_ARTIFACTS", "5"))
    TAVILY_API_KEY: str = os.getenv("TAVILY_API_KEY", "")

    FMP_API_KEY: str = os.getenv("FMP_API_KEY", "")

    # Gmail: paths to the OAuth client (credentials.json) and the saved
    # refresh token (token.json) generated by scripts/gmail_auth.py.
    GMAIL_CREDENTIALS_FILE: str = os.getenv("GMAIL_CREDENTIALS_FILE", "credentials.json")
    GMAIL_TOKEN_FILE: str = os.getenv("GMAIL_TOKEN_FILE", "token.json")

    SHOPIFY_ACCESS_TOKEN: str = os.getenv("SHOPIFY_ACCESS_TOKEN", "")
    SHOPIFY_AGENT_PROFILE: str = os.getenv(
        "SHOPIFY_AGENT_PROFILE",
        "https://shopify.dev/ucp/agent-profiles/examples/2026-04-08/valid-with-capabilities.json",
    )
    SHOPIFY_CLIENT_ID: str = os.getenv("SHOPIFY_CLIENT_ID", "")
    SHOPIFY_CLIENT_SECRET: str = os.getenv("SHOPIFY_CLIENT_SECRET", "")

    MEM0_API_KEY: str = os.getenv("MEM0_API_KEY", "")
    MEM0_USER_ID: str = os.getenv("MEM0_USER_ID", "user-1")

    NOTION_API_KEY: str = os.getenv("NOTION_API_KEY", "")
    NOTION_DATABASE_ID: str = os.getenv("NOTION_DATABASE_ID", "")

    USER_ID: str = os.getenv("USER_ID", "user-1")

    SUPABASE_URL: str = os.getenv("SUPABASE_URL", "")
    SUPABASE_KEY: str = os.getenv("SUPABASE_KEY", "")

    PINECONE_API_KEY: str = os.getenv("PINECONE_API_KEY", "")
    PINECONE_INDEX_NAME: str = os.getenv("PINECONE_INDEX_NAME", "conversations")
    PINECONE_CLOUD: str = os.getenv("PINECONE_CLOUD", "aws")
    PINECONE_REGION: str = os.getenv("PINECONE_REGION", "us-east-1")

    EMBEDDING_MODEL: str = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
    EMBEDDING_DIM: int = 384


settings = Settings()
